apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-transaction-app
  labels:
    app: banking-transaction-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-transaction-app
  template:
    metadata:
      labels:
        app: banking-transaction-app
    spec:
      containers:
      - name: my-nginx
        image: youneslabiod/bank-transaction-rest-api
        env:
        - name: DATABASE_URL
          value: jdbc:postgresql://bank-postgres:5432/bank
        - name: DATABASE_USER_NAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: mysecretpassword
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)