apiVersion: v1
kind: Service
metadata:
  name: banking-transaction-app
spec:
  selector:
    app: banking-transaction-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer