apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-transaction-app
  labels:
    app: banking-transaction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-transaction-app
  template:
    metadata:
      labels:
        app: banking-transaction-app
    spec:
      containers:
      - name: banking-transaction-app
        image: youneslabiod/bank-transaction-rest-api
        env:
          - name: DATABASE_URL
            value: jdbc:postgresql://postgres:5432/bank
          - name: DB_PORT
            value: "5432"
          - name: DATABASE_USER_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
            #value: postgres
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
            #value: mysecretpassword
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi" #128 MB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)


# kubectl create secret generic postgres-credentials --from-literal=username=postgres --from-literal=password=mysecretpassword
