apiVersion: v1
kind: Pod
metadata:
  name: banking-transaction-app
spec:
  containers:
  - name: banking-transaction-app
    image: youneslabiod/bank-transaction-rest-api
    env:
    - name: DATABASE_URL
      value: jdbc:postgresql://bank-postgres:5432/bank
    - name: DATABASE_USER_NAME
      value: postgres
    - name: DATABASE_PASSWORD
      value: mysecretpassword
    ports:
    - containerPort: 8080